"""Typed models of the Rubika API.

Every model is a keyword-only dataclass built on :class:`Object`; unknown
server keys are preserved in ``.extra``.  Bot API models live in
:mod:`rubigram.types.bot`.
"""

from rubigram.peer import Peer

from . import bot
from .channel import (
    AddChannelMembersResult,
    AddChannelResult,
    BanChannelMemberResult,
    Channel,
    ChannelInfo,
    ChannelLink,
    ChannelPreview,
    EditChannelInfoResult,
    JoinedChannel,
)
from .chat import (
    Chat,
    ChatAdsResult,
    ChatsResult,
    ChatsUpdates,
    ChatUpdate,
    DeleteChatHistoryResult,
    DeletedMessages,
    ForwardedMessages,
    MessageReadParticipants,
    MessagesResult,
    MessagesUpdates,
    SearchMessagesResult,
    SentMessage,
    ShareUrl,
    SocketChatUpdate,
)
from .files import (
    Avatar,
    AvatarFile,
    AvatarThumbnail,
    ChatAvatars,
    DownloadableFile,
    FileInline,
    Sticker,
    StickerFile,
    UploadDescriptor,
    UrlFile,
)
from .formatting import MessageEntity
from .group import (
    AddGroupMembersResult,
    AddGroupResult,
    AdminAccessList,
    BanGroupMemberResult,
    ChatReactionSetting,
    CreatedJoinLink,
    EditGroupInfoResult,
    Group,
    GroupDefaultAccess,
    GroupInfo,
    GroupLink,
    GroupMember,
    GroupMembers,
    GroupOnlineCount,
    GroupPreview,
    JoinedGroup,
    JoinLinkEntry,
    JoinLinkObject,
    JoinLinks,
    JoinRequest,
    JoinRequests,
    MentionList,
    OwnerRequestResult,
    PendingObjectOwner,
    SetGroupAdminResult,
)
from .message import (
    ContactMessage,
    EventData,
    ForwardedFrom,
    LiveData,
    LiveStatus,
    Location,
    Message,
    MessageMetadata,
    MessageUpdate,
    MetadataPart,
    ReactionCount,
    RubinoPostData,
    SocketMessageUpdate,
)
from .object import Object, model
from .raw_object import Empty, RawObject
from .rubino import BaseInfo, RubinoPost, RubinoPostMedia, RubinoPostsResult, RubinoStoriesResult, RubinoStory
from .settings import (
    ChangePhoneRequest,
    Folder,
    FolderResult,
    FoldersResult,
    MySessions,
    NotificationSetting,
    PrivacySetting,
    PrivacySettingResult,
    SessionInfo,
    TwoStepStatus,
    TwoStepStatusResult,
    UnconfirmedSession,
    UnconfirmedSessions,
    UserSetting,
    UserSettingResult,
)
from .stickers import (
    AvailableReaction,
    AvailableReactions,
    ChatReactions,
    GifSet,
    MessageReactions,
    Poll,
    PollOptionVoters,
    PollStatus,
    PollStatusResult,
    StickerSet,
    StickerSetResult,
    StickerSets,
    StickerSetting,
    UserMessageReaction,
)
from .update import DraftMessage, DraftMessageUpdate, NotificationMessageData, ShowActivity, ShowNotification, SocketUpdates, Updates
from .user import (
    AbsObjects,
    Authorization,
    BlockedUsers,
    CommonGroups,
    Contacts,
    ContactsLastOnline,
    ContactsUpdates,
    InlineOpenUrlData,
    ObjectByUsername,
    OnlineTime,
    PeerObject,
    ProfileLink,
    ProfileLinkItem,
    ProfileLinkItems,
    SearchGlobalObject,
    SearchGlobalObjectsResult,
    SentCode,
    TimeResult,
    UpdatedProfile,
    User,
    UserAdditionalInfo,
    UserInfo,
    UsernameCheck,
)

__all__ = [
    "Object",
    "model",
    "Peer",
    "MessageEntity",
    "RawObject",
    "Empty",
    "bot",
    # files
    "DownloadableFile",
    "FileInline",
    "StickerFile",
    "AvatarThumbnail",
    "AvatarFile",
    "Avatar",
    "ChatAvatars",
    "UploadDescriptor",
    "UrlFile",
    "Sticker",
    # users
    "OnlineTime",
    "PeerObject",
    "User",
    "UserAdditionalInfo",
    "UserInfo",
    "ContactsLastOnline",
    "ContactsUpdates",
    "Contacts",
    "BlockedUsers",
    "ObjectByUsername",
    "AbsObjects",
    "CommonGroups",
    "UsernameCheck",
    "UpdatedProfile",
    "SentCode",
    "Authorization",
    "InlineOpenUrlData",
    "ProfileLink",
    "ProfileLinkItem",
    "ProfileLinkItems",
    "SearchGlobalObject",
    "SearchGlobalObjectsResult",
    "TimeResult",
    # messages
    "ForwardedFrom",
    "RubinoPostData",
    "LiveStatus",
    "LiveData",
    "Location",
    "ContactMessage",
    "MetadataPart",
    "MessageMetadata",
    "EventData",
    "ReactionCount",
    "Message",
    "MessageUpdate",
    "SocketMessageUpdate",
    # chats
    "Chat",
    "ChatUpdate",
    "SocketChatUpdate",
    "ChatsResult",
    "ChatsUpdates",
    "SentMessage",
    "ForwardedMessages",
    "DeletedMessages",
    "DeleteChatHistoryResult",
    "MessagesResult",
    "MessagesUpdates",
    "SearchMessagesResult",
    "MessageReadParticipants",
    "ChatAdsResult",
    "ShareUrl",
    # groups
    "ChatReactionSetting",
    "Group",
    "GroupMember",
    "GroupMembers",
    "GroupInfo",
    "GroupDefaultAccess",
    "AdminAccessList",
    "PendingObjectOwner",
    "GroupLink",
    "JoinLinkObject",
    "JoinLinkEntry",
    "JoinLinks",
    "CreatedJoinLink",
    "JoinRequest",
    "JoinRequests",
    "AddGroupResult",
    "EditGroupInfoResult",
    "BanGroupMemberResult",
    "SetGroupAdminResult",
    "AddGroupMembersResult",
    "GroupPreview",
    "JoinedGroup",
    "GroupOnlineCount",
    "MentionList",
    "OwnerRequestResult",
    # channels
    "Channel",
    "ChannelInfo",
    "AddChannelResult",
    "AddChannelMembersResult",
    "EditChannelInfoResult",
    "BanChannelMemberResult",
    "ChannelLink",
    "ChannelPreview",
    "JoinedChannel",
    # updates
    "ShowActivity",
    "NotificationMessageData",
    "ShowNotification",
    "DraftMessage",
    "DraftMessageUpdate",
    "Updates",
    "SocketUpdates",
    # settings
    "PrivacySetting",
    "PrivacySettingResult",
    "NotificationSetting",
    "UserSetting",
    "UserSettingResult",
    "TwoStepStatus",
    "TwoStepStatusResult",
    "SessionInfo",
    "MySessions",
    "UnconfirmedSession",
    "UnconfirmedSessions",
    "Folder",
    "FoldersResult",
    "FolderResult",
    "ChangePhoneRequest",
    # stickers / reactions / polls
    "StickerSet",
    "StickerSets",
    "StickerSetResult",
    "StickerSetting",
    "GifSet",
    "AvailableReaction",
    "AvailableReactions",
    "UserMessageReaction",
    "MessageReactions",
    "ChatReactions",
    "PollStatus",
    "Poll",
    "PollStatusResult",
    "PollOptionVoters",
    # rubino
    "RubinoPostMedia",
    "RubinoPost",
    "RubinoPostsResult",
    "RubinoStory",
    "RubinoStoriesResult",
    "BaseInfo",
]
