# Generated by Django 5.2.14 on 2026-09-08 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WorkerSignedNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=128, unique=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_order_id", models.BigIntegerField(db_index=True)),
                ("idempotency_key", models.CharField(max_length=128, unique=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("join", "Join"),
                            ("leave", "Leave"),
                            ("view", "View"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target", models.CharField(max_length=512)),
                ("target_key", models.CharField(max_length=512)),
                ("object_guid", models.CharField(blank=True, max_length=64)),
                ("requested_count", models.PositiveIntegerField()),
                ("total_count", models.PositiveIntegerField(default=0)),
                ("accepted_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_count", models.PositiveIntegerField(default=0)),
                (
                    "member_count_before",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "member_count_after",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("inprogress", "In progress"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("partial", "Partial"),
                            ("fail", "Fail"),
                            ("error", "Error"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("service_id", models.CharField(blank=True, max_length=16)),
                ("retention_days", models.PositiveIntegerField(blank=True, null=True)),
                ("callback_url", models.URLField(max_length=1024)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="worker_memb_status_9f026c_idx",
                    ),
                    models.Index(
                        fields=["target_key", "status"],
                        name="worker_memb_target__214243_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WorkerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=128)),
                ("phone", models.CharField(max_length=32)),
                ("session_name", models.CharField(max_length=255, unique=True)),
                ("user_guid", models.CharField(blank=True, max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="worker_work_status_8255f4_idx",
                    ),
                    models.Index(fields=["phone"], name="worker_work_phone_9d107b_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MembershipJobItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("group_title", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="worker.membershipjob",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_items",
                        to="worker.workeraccount",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AccountThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_available_at", models.DateTimeField(blank=True, null=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="throttle",
                        to="worker.workeraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerAccountCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_string", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credential",
                        to="worker.workeraccount",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkerAutoLeaveSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target", models.CharField(max_length=512)),
                ("target_key", models.CharField(max_length=512)),
                ("due_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("fail", "Fail"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_leave_schedules",
                        to="worker.workeraccount",
                    ),
                ),
                (
                    "source_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_leave_schedule",
                        to="worker.membershipjobitem",
                    ),
                ),
                (
                    "source_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_leave_schedules",
                        to="worker.membershipjob",
                    ),
                ),
            ],
            options={
                "ordering": ["due_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkerMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_key", models.CharField(max_length=512)),
                ("target_display", models.CharField(max_length=512)),
                ("object_guid", models.CharField(blank=True, max_length=64)),
                ("object_type", models.CharField(blank=True, max_length=16)),
                ("group_title", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("joined", "Joined"), ("left", "Left")],
                        default="left",
                        max_length=16,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="worker.workeraccount",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="membershipjobitem",
            index=models.Index(fields=["job", "status"], name="worker_memb_job_id_0ddcdd_idx"),
        ),
        migrations.AddIndex(
            model_name="membershipjobitem",
            index=models.Index(fields=["account", "status"], name="worker_memb_account_7e12b3_idx"),
        ),
        migrations.AddIndex(
            model_name="workerautoleaveschedule",
            index=models.Index(fields=["status", "due_at"], name="worker_work_status_5df77b_idx"),
        ),
        migrations.AddIndex(
            model_name="workermembership",
            index=models.Index(fields=["target_key", "status"], name="worker_work_target__ce3750_idx"),
        ),
        migrations.AddConstraint(
            model_name="workermembership",
            constraint=models.UniqueConstraint(fields=("account", "target_key"), name="uniq_worker_account_target"),
        ),
    ]
