# Generated by Django 5.2.17 on 2026-09-08 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerAccountHealth",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "availability",
                    models.CharField(
                        choices=[("available", "Available"), ("at_capacity", "At capacity"), ("dead", "Dead"), ("unknown", "Unknown")],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("outcome", models.CharField(blank=True, max_length=16)),
                ("detail", models.TextField(blank=True)),
                ("consecutive_auth_failures", models.PositiveIntegerField(default=0)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="health", to="worker.workeraccount"),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["availability"], name="worker_work_availab_201a9b_idx"),
                    models.Index(fields=["last_checked_at"], name="worker_work_last_ch_5f6f8b_idx"),
                ],
            },
        ),
    ]
