# Generated by Django 5.2.17 on 2026-09-30 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("worker", "0002_account_health"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerPostView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target_key", models.CharField(max_length=512)),
                ("viewed_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="post_views", to="worker.workeraccount"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["target_key", "viewed_at"], name="worker_work_target__e4386e_idx")],
                "constraints": [models.UniqueConstraint(fields=("account", "target_key"), name="uniq_worker_view_account_target")],
            },
        ),
    ]
